# Site Params

# Open Graph, Twitter Cards and schema.org Thing and Article (in posts)
# https://gohugo.io/templates/internal/#open-graph
# https://gohugo.io/templates/internal/#twitter-cards
# https://schema.org/Thing
# https://schema.org/Article
description = "Mi nombre es Victor S. Recio. Soy arquitecto de software, líder técnico y KubeAstronaut certificado, especializado en Microsoft Azure, DevOps, SRE y el ecosistema cloud-native. Mi enfoque es ayudar a equipos a crear sistemas escalables, resilientes y seguros a través de la automatización, contenedores y las mejores prácticas de la arquitectura de software."
images = ['images/logo.svg','images/site-feature-image.png']
mainMenuLogo = "images/logo.svg"

# For favicons
## Chrome Browser
themeColor = "#fff"

# Alert
# alert = false
# alertDismissable = true
# alertText = "Introducing this new service! <a class=\"alert-link stretched-link\" href=\"https://salvus.site/\">Check out Total Security</a>"

# Pre-footer
# footerAbout = true
# footerAboutTitle = "Few Words About Us"
# footerAboutText = "We protect your website so you can provide a safe environment to build trust and improve the user experience of your visitors.<br/><br/>Salvus Site is the partner that you can rely on for preventive and reactive cybersecurity."

[options]
  bootStrapJs = true
  breadCrumb = true
  listCategoryFilter = true
  listTagFilter = true
