[[main]]
name = "Home"
url = "/"
weight = 1

# [[main]]
# name = "About"
# url = "about"
# weight = 4
#title = "Made with ❤️ by the Hugo Bootstrap Theme team"

# [[main]]
# url = "speaking"
# name = "speaking"
# weight = 3

[[main]]
url = "writing"
name = "Writing"
weight = 4

[[main]]
url = "resources"
name = "Resources"
weight = 5

# [[main]]
# url = "videos"
# name = "videos"
# weight = 6

[[main]]
url = "patreon"
name = "patreon"
weight = 7


# [[main]]
# name = "All"
# url = "post"
# weight = 100
# parent = "blog"

# [[main]]
# name = "Hugo"
# url = "tags/hugo"
# weight = 20
# parent = "blog"

# [[main]]
# name = "Bootstrap"
# url = "tags/bootstrap"
# weight = 30
# parent = "blog"


# [[social]]
#   name = "GitHub"
#   pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-github'><use href='/hugo-bootstrap-theme/images/feather/feather-sprite.svg#github'/></svg>"
#   url = "https://github.com/filipecarneiro/hugo-bootstrap-theme/"
#   weight = 10
#   title = "Visit the GitHub project"

# [[social]]
#   name = "Twitter"
#   pre = "<svg xmlns='http://www.w3.org/2000/svg' class='feather feather-twitter'><use href='/hugo-bootstrap-theme/images/feather/feather-sprite.svg#twitter'/></svg>"
#   url = "https://twitter.com/jfilipecarneiro/"
#   weight = 20
#   title = "Contact on Twitter"
