[[main]]
name = "Inicio"
url = "/"
weight = 10

[[main]]
name = "Artículos"
url = "/writing/"
weight = 20

[[main]]
name = "Cursos"
url = "/cursos/"
weight = 30

[[main]]
name = "Recursos"
url = "/resources/"
weight = 35

[[main]]
name = "Conferencias"
url = "/#conferencias"
weight = 40
